# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.4
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-01-01T22:45:19Z"
  labels:
    app: wp
  name: wp
spec:
  ports:
  - name: "3306"
    nodePort: 32477
    port: 3306
    targetPort: 3306
  - name: "80"
    nodePort: 30985
    port: 80
    targetPort: 80
  selector:
    app: wp
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-01-01T22:45:19Z"
  labels:
    app: wp
  name: wp
spec:
  containers:
  - args:
    - mysqld
    image: docker.io/mysql/mysql-server:8.0
    name: mysql-server
    ports:
    - containerPort: 3306
      hostPort: 3306
    - containerPort: 80
      hostPort: 8080
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
  - args:
    - apache2-foreground
    image: docker.io/library/wordpress:latest
    name: wordpress
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /var/www/html
      name: 0307da08d5bea1de39cacf05ea9f26a19c6af761c786fb8375bddef7d5d84360-pvc
  restartPolicy: Never
  volumes:
  - name: 0307da08d5bea1de39cacf05ea9f26a19c6af761c786fb8375bddef7d5d84360-pvc
    persistentVolumeClaim:
      claimName: 0307da08d5bea1de39cacf05ea9f26a19c6af761c786fb8375bddef7d5d84360
status: {}

