apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wordpress
  creationTimestamp: null
  labels:
    io.kompose.service: db-data
  name: db-data
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: db-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
