apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: wordpress
  name: db-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/db-data"