apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: wordpress
data:
  # Thess values are base64-encoded. Do not use this passwords in production!
  password: "ZKk9eVOFMwTdGs/5RBgzoA=="
  root_password: "I1kO7Kh920FqTQivyjt7vQ=="