apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: wordpress
  name: wordpress-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/wordpress-data"